/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;


import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());

    }

@Test public void testIfIsWriteToFile (){
    String path ="src/main/resources/data.json";
    Quotes readFromFile = new Quotes();
    readFromFile.read(path);

    ApiQuotes getNewQuote = new ApiQuotes();
    getNewQuote.sendGetRequest();
            Quotes readFromFileWithNewQuote = new Quotes();
            readFromFileWithNewQuote.read(path);
            assertEquals("check if write new lin to thr file",readFromFile.getQuotes().length+1,readFromFileWithNewQuote.getQuotes().length);



}


}
