/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;


import java.io.IOException;


public class App {
    public static void main(String[] args) {
        Quotes quotes = new Quotes();
        String path ="app/src/test/resources/test.json";
//                "app/src/main/resources/data.json";

            quotes.read(path);
            quotes.reandomQuote( quotes.random());
        System.out.println(quotes.getQuotes()[0].getAuthor());


    }
}
