/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

public class App {
    public static void main(String[] args) {
//String url ="http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en";
ApiQuotes quotes = new ApiQuotes();
        quotes.sendGetRequest();


    }



}
